/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
  surface: "#FBF6EC",
  "surface-dim": "#F3E9D4",
  "surface-bright": "#FFFFFF",
  "surface-container-lowest": "#FFFFFF",
  "surface-container-low": "#F7F0E2",
  "surface-container": "#F3E9D4",
  "surface-container-high": "#EADCBE",
  "surface-container-highest": "#DFCBA0",
  "on-surface": "#2B1D12",
  "on-surface-variant": "#7A6B52",
  "inverse-surface": "#442D1C",
  "inverse-on-surface": "#FBF6EC",
  outline: "#9D9167",
  "outline-variant": "#DFCBA0",
  "surface-tint": "#84592B",
  primary: "#84592B",
  "on-primary": "#FFFFFF",
  "primary-container": "#84592B",
  "on-primary-container": "#FFFFFF",
  "inverse-primary": "#E8D1A7",
  secondary: "#9D9167",
  "on-secondary": "#FFFFFF",
  "secondary-container": "#E8E2CC",
  "on-secondary-container": "#442D1C",
  tertiary: "#743014",
  "on-tertiary": "#FFFFFF",
  "tertiary-container": "#F5E0D6",
  "on-tertiary-container": "#743014",
  error: "#A8351A",
  "on-error": "#FFFFFF",
  "error-container": "#F5DAD2",
  "on-error-container": "#A8351A",
  background: "#FBF6EC",
  "on-background": "#2B1D12",
  "surface-variant": "#F3E9D4",
  "border-slate": "#DFCBA0",
  "level0-bg": "#FBF6EC",
  "level1-card": "#FFFFFF",
  "level2-input": "#FFFFFF",
  dark: "#442D1C",
  "on-dark": "#FBF6EC",
  "dark-muted": "#C4AD8C",
  gold: "#E8D1A7",
  olive: "#9D9167",
  caramel: "#84592B",
  wine: "#743014",
  cocoa: "#442D1C",
},
      fontFamily: {
        sans: ["DMSans_400Regular"],
        "sans-medium": ["DMSans_500Medium"],
        "sans-bold": ["DMSans_700Bold"],
        mono: ["DMMono_400Regular"],
        "mono-bold": ["DMMono_500Medium"],
      },
      fontSize: {
        "display-lg": ["34px", { lineHeight: "42px", letterSpacing: "-0.4px" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.2px" }],
        "body-base": ["15px", { lineHeight: "22px" }],
        "body-bold": ["15px", { lineHeight: "22px" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.9px" }],
        "stat-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.4px" }],
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "margin-mobile": "20px",
      },
    },
  },
  plugins: [],
};