/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#FAF7F2",
        "surface-dim": "#F0EBE3",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F5F1EA",
        "surface-container": "#F0EBE3",
        "surface-container-high": "#E8E0D5",
        "surface-container-highest": "#DDD2C2",
        "on-surface": "#1A1A1A",
        "on-surface-variant": "#6B6B6B",
        "inverse-surface": "#2C1A0E",
        "inverse-on-surface": "#FAF7F2",
        outline: "#A89080",
        "outline-variant": "#E8E0D5",
        "surface-tint": "#C4622D",
        primary: "#C4622D",
        "on-primary": "#FFFFFF",
        "primary-container": "#C4622D",
        "on-primary-container": "#FFFFFF",
        "inverse-primary": "#E8956B",
        secondary: "#8A5A32",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#E8E0D5",
        "on-secondary-container": "#2C1A0E",
        tertiary: "#A8501F",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#FDEAE0",
        "on-tertiary-container": "#A8501F",
        error: "#D94F4F",
        "on-error": "#FFFFFF",
        "error-container": "#FDEAEA",
        "on-error-container": "#D94F4F",
        background: "#FAF7F2",
        "on-background": "#1A1A1A",
        "surface-variant": "#F0EBE3",
        "border-slate": "#E8E0D5",
        "level0-bg": "#FAF7F2",
        "level1-card": "#FFFFFF",
        "level2-input": "#FFFFFF",
        dark: "#2C1A0E",
        "on-dark": "#FAF7F2",
        "dark-muted": "#A89080",
      },
      fontFamily: {
        sans: ["DMSans_400Regular"],
        "sans-medium": ["DMSans_500Medium"],
        "sans-bold": ["DMSans_700Bold"],
        mono: ["DMMono_400Regular"],
        "mono-bold": ["DMMono_500Medium"],
      },
      fontSize: {
        "display-lg": ["34px", { lineHeight: "42px", letterSpacing: "-0.4px" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.2px" }],
        "body-base": ["15px", { lineHeight: "22px" }],
        "body-bold": ["15px", { lineHeight: "22px" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.9px" }],
        "stat-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.4px" }],
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "margin-mobile": "20px",
      },
    },
  },
  plugins: [],
};