/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#0f131c",
        "surface-dim": "#0f131c",
        "surface-bright": "#353943",
        "surface-container-lowest": "#0a0e17",
        "surface-container-low": "#181b25",
        "surface-container": "#1c1f29",
        "surface-container-high": "#262a34",
        "surface-container-highest": "#31353f",
        "on-surface": "#dfe2ef",
        "on-surface-variant": "#e2bfb0",
        "inverse-surface": "#dfe2ef",
        "inverse-on-surface": "#2c303a",
        outline: "#a98a7d",
        "outline-variant": "#5a4136",
        "surface-tint": "#ffb693",
        primary: "#ffb693",
        "on-primary": "#561f00",
        "primary-container": "#ff6b00",
        "on-primary-container": "#572000",
        "inverse-primary": "#a04100",
        secondary: "#4edea3",
        "on-secondary": "#003824",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        tertiary: "#ffb3ad",
        "on-tertiary": "#68000a",
        "tertiary-container": "#ff6762",
        "on-tertiary-container": "#6a000b",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#0f131c",
        "on-background": "#dfe2ef",
        "surface-variant": "#31353f",
        "border-slate": "#1f2d44",
        "level0-bg": "#090d16",
        "level1-card": "#121926",
        "level2-input": "#1a2436",
      },
      fontFamily: {
        sans: ["DMSans_400Regular"],
        "sans-medium": ["DMSans_500Medium"],
        "sans-bold": ["DMSans_700Bold"],
        mono: ["DMMono_400Regular"],
        "mono-bold": ["DMMono_500Medium"],
      },
      fontSize: {
        "display-lg": ["34px", { lineHeight: "42px", letterSpacing: "-0.4px" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.2px" }],
        "body-base": ["15px", { lineHeight: "22px" }],
        "body-bold": ["15px", { lineHeight: "22px" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.9px" }],
        "stat-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.4px" }],
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
      },
    },
  },
  plugins: [],
};
